### ISSUE TITLE
File upload seems to pass an array to escape helper

### ISSUE THREAD

**Issue by driehle** [neilime/twbs-helper-module#72]
**Describe the bug**

Using a file upload, I get the following error when validation fails and the form is supposed to be rendered:

```
Laminas\View\Exception\InvalidArgumentException

File:

    APP_PATH\vendor\laminas\laminas-view\src\Helper\Escaper\AbstractHelper.php:55

Message:

    Array provided to Escape helper, but flags do not allow recursion

Stack trace:

    #0 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\AbstractHelper.php(271): Laminas\View\Helper\Escaper\AbstractHelper->__invoke(Array)
    #1 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\FormInput.php(134): Laminas\Form\View\Helper\AbstractHelper->createAttributesString(Array)
    #2 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\FormFile.php(22): Laminas\Form\View\Helper\FormInput->render(Object(Laminas\Form\Element\File))
    #3 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\FormInput.php(103): TwbsHelper\Form\View\Helper\FormFile->render(Object(Laminas\Form\Element\File))
    #4 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\FormElement.php(100): Laminas\Form\View\Helper\FormInput->__invoke(Object(Laminas\Form\Element\File))
    #5 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\FormElement.php(207): TwbsHelper\Form\View\Helper\FormElement->renderHelper('formfile', Object(Laminas\Form\Element\File))
    #6 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\FormElement.php(116): Laminas\Form\View\Helper\FormElement->renderType(Object(Laminas\Form\Element\File))
    #7 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\FormElement.php(71): Laminas\Form\View\Helper\FormElement->render(Object(Laminas\Form\Element\File))
    #8 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\FormRow.php(194): TwbsHelper\Form\View\Helper\FormElement->render(Object(Laminas\Form\Element\File))
    #9 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\FormRow.php(91): TwbsHelper\Form\View\Helper\FormRow->renderElement(Object(Laminas\Form\Element\File), 'prepend')
    #10 APP_PATH\vendor\laminas\laminas-form\src\View\Helper\FormRow.php(116): TwbsHelper\Form\View\Helper\FormRow->render(Object(Laminas\Form\Element\File), 'prepend')
    #11 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\Form.php(152): Laminas\Form\View\Helper\FormRow->__invoke(Object(Laminas\Form\Element\File))
    #12 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\Form.php(77): TwbsHelper\Form\View\Helper\Form->renderElements(Object(Application\Form\EditEmployeeContract))
    #13 APP_PATH\vendor\neilime\twbs-helper-module\src\TwbsHelper\Form\View\Helper\Form.php(47): TwbsHelper\Form\View\Helper\Form->render(Object(Application\Form\EditEmployeeContract))
    #14 [internal function]: TwbsHelper\Form\View\Helper\Form->__invoke(Object(Application\Form\EditEmployeeContract), NULL)
    #15 APP_PATH\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php(396): call_user_func_array(Object(TwbsHelper\Form\View\Helper\Form), Array)
    #16 APP_PATH\module\Application\view\application\employee-contract\create.phtml(6): Laminas\View\Renderer\PhpRenderer->__call('form', Array)
    #17 APP_PATH\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php(505): include('C:\\Users\\Dennis...')
    #18 APP_PATH\vendor\laminas\laminas-view\src\View.php(206): Laminas\View\Renderer\PhpRenderer->render(NULL)
    #19 APP_PATH\vendor\laminas\laminas-view\src\View.php(235): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
    #20 APP_PATH\vendor\laminas\laminas-view\src\View.php(199): Laminas\View\View->renderChildren(Object(Laminas\View\Model\ViewModel))
    #21 APP_PATH\vendor\laminas\laminas-mvc\src\View\Http\DefaultRenderingStrategy.php(104): Laminas\View\View->render(Object(Laminas\View\Model\ViewModel))
    #22 APP_PATH\vendor\laminas\laminas-eventmanager\src\EventManager.php(321): Laminas\Mvc\View\Http\DefaultRenderingStrategy->render(Object(Laminas\Mvc\MvcEvent))
    #23 APP_PATH\vendor\laminas\laminas-eventmanager\src\EventManager.php(170): Laminas\EventManager\EventManager->triggerListeners(Object(Laminas\Mvc\MvcEvent))
    #24 APP_PATH\vendor\laminas\laminas-mvc\src\Application.php(366): Laminas\EventManager\EventManager->triggerEvent(Object(Laminas\Mvc\MvcEvent))
    #25 APP_PATH\vendor\laminas\laminas-mvc\src\Application.php(347): Laminas\Mvc\Application->completeRequest(Object(Laminas\Mvc\MvcEvent))
    #26 APP_PATH\public\index.php(37): Laminas\Mvc\Application->run()
    #27 {main}
```

The following attributes are trying to be escaped. The attribute `value` causes the issue here:

```
array(4) {
  ["type"]=>
  string(4) "file"
  ["name"]=>
  string(4) "file"
  ["class"]=>
  string(17) "form-control-file"
  ["value"]=>
  array(5) {
    ["name"]=>
    string(24) "Guide-for-Presenters.pdf"
    ["type"]=>
    string(15) "application/pdf"
    ["tmp_name"]=>
    string(46) "C:\Users\Dennis\AppData\Local\Temp\php13AD.tmp"
    ["error"]=>
    int(0)
    ["size"]=>
    int(1104622)
  }
}
```

**Steps to reproduce**

A simple form with a file element and the following code in the controller:

```
        if ($request->isPost()) {
            $post = array_merge_recursive(
                $request->getPost()->toArray(),
                $request->getFiles()->toArray()
            );
            $form->setData($post);

            if ($form->isValid()) {
                 ....
            }
        }
```

View script:

```
<?php
echo $this->form($this->form, null);
?>
```

**Suggested solution**

I think the class `TwbsHelper\Form\View\Helper\FormFile` should not extend from `\Laminas\Form\View\Helper\FormInput` but from `\Laminas\Form\View\Helper\FormFile`. If I change this manually, everything works again.

**Comment by neilime** [comment]
I will fix it in the next days

**Comment by neilime** [comment]
Fixed in new release: https://github.com/neilime/twbs-helper-module/releases/tag/v3.3.0

**Comment by driehle** [comment]
Thanks @neilime, works like a charme with v.3.3.0.
